---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
options(scipen = 99) # me-non-aktifkan scientific notation
library(tidyverse) # koleksi beberapa package R
library(dplyr) # grammar of data manipulation
library(readr) # membaca data
library(ggplot2) # plot statis
library(plotly) # plot interaktif
library(glue) # setting tooltip
library(scales) # mengatur skala pada plot
```

```{r}
Video <- read_csv("C:/Users/Rima Sugiarto/Documents/Theia/LBB 1/youtube-analysis-theia/data_input/youtubetrends.csv")

#data Video_clean
Video_clean <- 
  Video %>% 
  mutate(
    channel_title = as.factor(channel_title),
    category_id = as.factor(category_id),
    publish_when = as.factor(publish_when),
    publish_wday = as.factor(publish_wday),
    timetotrend = as.factor(timetotrend),
    
    likesp = likes/views,
    dislikesp = dislikes/views,
    commentp = comment_count/views
  )
```



Column {data-width=500}
-------------------------------------------------------------------

### Trending Video Category

```{r}
#dive deeper Video_count 
Video_count <- 
  Video_clean %>% 
  group_by(category_id) %>% 
  summarise(count_Video = n()) %>% # n() -> untuk menghitung frekuensi
  arrange(desc(count_Video))

#data
Video_count <- 
  Video_count %>% 
  mutate(label = glue("Category Video : {category_id}
                      Total Video : {count_Video}"))

#ggplot
plot1 <- ggplot(data = Video_count, 
       mapping = aes(x = count_Video, 
                     y = reorder(category_id, count_Video),
                     text = label)) + 
  geom_col(aes(fill = count_Video), show.legend = F) +
  scale_fill_gradient(low = "red", high = "black") +
  labs(
    title = "Trending Categories on YouTube US 2017",
    y = "",
    x = "Video Count"
  ) +
  theme_minimal()

#ggplotly
ggplotly(plot1, tooltip = "text")
```

Column {data-width=500}
-------------------------------------------------------------------

### Entertainment YouTube Channel

```{r}
#dive deeper vids_top_channel
Video_top_channel <- 
  Video_clean %>% 
  filter(category_id == "Entertainment") %>% 
  group_by(channel_title) %>% 
  summarise(total_views = sum(views)) %>% 
  arrange(desc(total_views)) %>% 
  head(10)

#data
Video_top_channel <- 
  Video_top_channel %>% 
  mutate(label = glue("Channel Title : {channel_title}
                      Total views : {comma(total_views)}"))

#ggplot
plot2 <- ggplot(data = Video_top_channel, 
       mapping = aes(x = total_views, 
                     y = reorder(channel_title, total_views),
                     color = total_views,
                     text = label)) + 
  geom_point(size = 1) +
  geom_segment(aes(x = 2,xend = total_views, yend = channel_title), size = 2)+
  scale_color_gradient(low = "red", high = "black") +
  labs(
    title = "Top 10 YouTube Channel in Entertainment",
    y = "",
    x = "Total Views") +
  theme_minimal() +
  theme(
    legend.position = "none"
  ) +
  scale_x_continuous(labels = comma)

#ggplotly
ggplotly(plot2, tooltip = "text")
```

### Viewers Activity

```{r}
#data
Video_trend <- 
  Video_clean %>%
  filter(category_id == "Entertainment") %>% 
  group_by(publish_hour) %>%
  summarise(mean_views = mean(views)) %>% 
  mutate(label = glue("Publish Hour : {publish_hour}
                      Average Views : {comma(mean_views)}"))

#ggplot
plot3 <- 
  ggplot(data = Video_trend, 
         mapping = aes(x=publish_hour,
                       y=mean_views)) +
  geom_line( color="red", size=1, linetype=1) +
  geom_point(color="black", size=2, aes(text = label)) +
  labs(
    title = "Viewers Activity for Entertainment Videos",
    y = "Views",
    x = "Publish Hour") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = seq(0,25,3)) +
  theme_minimal()

#ggplotly
ggplotly(plot3, tooltip = "text")
```